const allCourses = [
    {
      id: 1,
      free: true,
      name: "Design",
      title: "Typography in web design: Enhancing UI/UX web apps",
      level: "Professional",
      courseType: "Professional",
      subcategory: "Web Design",
      time: "6 months",
      date: "Jan 24, 2024",
      previewImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop",
      previewVideo: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
      hasVideo: true,
      instructor: "Juanita Bell",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 0,
      originalPrice: 0,
      rating: 4.7,
      students: 1250,
      description: "Master the art of typography in web design and create stunning UI/UX experiences.",
      tags: ["Typography", "UI/UX", "Web Design", "Frontend"],
    },
    {
      id: 2,
      free: false,
      name: "Development",
      title: "Software Development Fundamentals",
      level: "Monthly crash course",
      courseType: "Monthly crash course",
      subcategory: "Software Development",
      time: "3 months",
      date: "Jan 23, 2024",
      previewImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "Mike Chen",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 149,
      originalPrice: 199,
      rating: 4.8,
      students: 1345,
      description: "Learn software development from scratch with modern practices.",
      tags: ["Software Development", "Programming", "Coding"],
    },
    {
      id: 3,
      free: true,
      name: "Development",
      title: "Web Development Bootcamp",
      level: "Professional",
      courseType: "Professional",
      subcategory: "Web development",
      time: "12 months",
      date: "Jan 04, 2024",
      previewImage: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=300&fit=crop",
      previewVideo: "https://sample-videos.com/zip/10/mp4/SampleVideo_640x360_1mb.mp4",
      hasVideo: true,
      instructor: "Sarah Johnson",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 0,
      originalPrice: 0,
      rating: 4.9,
      students: 574,
      description: "Complete web development course covering frontend and backend.",
      tags: ["Web Development", "HTML", "CSS", "JavaScript"],
    },
    {
      id: 4,
      free: false,
      name: "Development",
      title: "Mobile App Development",
      level: "Hourly crash course",
      courseType: "Hourly crash course",
      subcategory: "Mobile Development",
      time: "8 months",
      date: "Feb 15, 2024",
      previewImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "Alex Rodriguez",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 89,
      originalPrice: 129,
      rating: 4.6,
      students: 317,
      description: "Build mobile apps for iOS and Android platforms.",
      tags: ["Mobile Development", "React Native", "Flutter"],
    },
    {
      id: 5,
      free: true,
      name: "Development",
      title: "No-Code Development Mastery",
      level: "Professional",
      courseType: "Professional",
      subcategory: "No-Code Development",
      time: "4 months",
      date: "Mar 10, 2024",
      previewImage: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "Emma Wilson",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 0,
      originalPrice: 0,
      rating: 4.5,
      students: 37,
      description: "Create applications without traditional coding.",
      tags: ["No-Code", "Automation", "Web Apps"],
    },
    {
      id: 6,
      free: false,
      name: "Data Science",
      title: "Data Science Fundamentals",
      level: "Professional",
      courseType: "Professional",
      subcategory: "Data Analysis",
      time: "6 months",
      date: "Apr 05, 2024",
      previewImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "Dr. Sarah Kim",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 199,
      originalPrice: 299,
      rating: 4.7,
      students: 892,
      description: "Master data science concepts and tools.",
      tags: ["Data Science", "Python", "Analytics"],
    },
    {
      id: 7,
      free: true,
      name: "Personal Development",
      title: "Leadership Skills Development",
      level: "Monthly crash course",
      courseType: "Monthly crash course",
      subcategory: "Leadership",
      time: "3 months",
      date: "Apr 10, 2024",
      previewImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "John Smith",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 0,
      originalPrice: 0,
      rating: 4.4,
      students: 456,
      description: "Develop essential leadership and management skills.",
      tags: ["Leadership", "Management", "Soft Skills"],
    },
    {
      id: 8,
      free: false,
      name: "Design",
      title: "UI/UX Design Masterclass",
      level: "Professional",
      courseType: "Professional",
      subcategory: "UI/UX Design",
      time: "8 months",
      date: "Apr 15, 2024",
      previewImage: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=300&fit=crop",
      previewVideo: null,
      hasVideo: false,
      instructor: "Maria Garcia",
      avatar: "/placeholder.svg?height=32&width=32",
      price: 179,
      originalPrice: 249,
      rating: 4.8,
      students: 723,
      description: "Complete UI/UX design course with real projects.",
      tags: ["UI/UX", "Design", "Figma", "Prototyping"],
    },
  ]


  export default allCourses;